### PR TITLE
2018.2

### PR DESCRIPTION
**Pull request by meandean420**
Can i please have a pull request of this ver.. 
thanks
dean

### CODE REVIEW

**Comment by sameera** [comment]
Hey Dean
These comments are quite old and already in master. May I know what you are looking for?

**Comment by meandean420** [comment]
Im looking for ServiceManager.dll ver. https://github.com/pro-celigo/lib-netsuite-servicemgr/tree/2018.2 would be kool.
I need .net ver all my code is .net and I have 5-6 app, I talk to netsuite with.. this would keep me running till I find more time
To move to net.core..

Thanks
dean

**Comment by sameera** [comment]
Got it. You are looking for the last .NET Framework compatible version (as opposed to the .NET Core compatible latest versions). Would you be able to use this nuget package instead of building from source?
https://www.nuget.org/packages/Celigo.SuiteTalk/3.4.0

**Comment by meandean420** [comment]
Sorry im not good with nuget packages.

But yes im looking for the last .NET Ver..

Like I went up to the old 2015.2 code and just download zip it had the code
I complied in vs 2010 move the dll into the apps.

Thanks
dean

**Comment by sameera** [comment]
Just made a tag for 3.4.0:
https://github.com/pro-celigo/lib-netsuite-servicemgr/releases/tag/v3.4.0

Please note that this is not entirely source compatible with
https://github.com/celigo/netsuite-service-manager-dotnet
You can make it work with a bit of changes, though. So, if you are looking
to update an app that was using the old library to 2018.2, you may need to
make a few code adjustments around how ServiceManager classes were
constructed. Rest of the code should remain the same.

Thanks.
Sameera

**Comment by sameera** [comment]
Dean
Out master branch is now back on .net standard 2.0. 
Hope this resolves your issue.

**Pull request closed without merging**
