### PR TITLE
Updated web service reference

### PR DESCRIPTION
**Pull request by ShamsulAmry**
TransactionPaymentEventType._sale is missing. I updated the web service reference just to make it work.

### CODE REVIEW

**Comment by sameera** [comment]
Thanks @ShamsulAmry 
We will be reviewing this. The original TransactionPayemntEventType enum generated by svcutil looks quite strange. Possible there was a bug in the tool.

**Comment by ShamsulAmry** [comment]
Or maybe NetSuite changed its WSDL after the fact?

**Comment by ShamsulAmry** [comment]
Do take note of the commit message. After running svcutil, there is there abstract method not implemented, so I make it to simply throw NotImplementedException.

**Comment by sameera** [comment]
@ShamsulAmry Apologies: I will be closing this PR without merging as we have done the WSDL refresh on our end as well. This refresh has resolved your original issue as well. As you have noted, there's a code generation we do on our side when we do a WSDL refresh. We've not had the bandwidth to open source that generator and therefore, we are unable make it possible for others to refresh the WSDLs on their own without introducing issues (as you ran in to). Apologies for this again.

**Pull request closed without merging**
